= Information Collector
:toc: left
:stylesdir: ../styles/
:stylesheet: monospace.css
:icons: font
:doctype: book

Just a collection of interresting stuff ;-)


== asdf for github actions

https://github.com/asdf-vm/asdf
https://github.com/asdf-vm/actions


== Cloud Deployments and DB State

One way to prevent an old version from breaking, is to split a migration into multiple steps.

E.g. you want to rename a column in the database. Renaming the column directly would break old versions of the app. This can be organized in multiple steps:

    Add a db migration that inserts the new column
    Change the app so that all writes go to the old and new column
    Run a task that copies all values from the old to the new column
    Change the app that it reads from the new column
    Add a migration that remove the old column

This is unfortunately quite a hassle, but prevents having a downtime with a maintenance page up.



https://bytes.grubhub.com/a-migration-story-471be2977b0e


https://martinfowler.com/bliki/BlueGreenDeployment.html

https://www.weave.works/blog/how-to-correctly-handle-db-schemas-during-kubernetes-rollouts

https://cloudnativedevopsblog.com/posts/database-migrations/



== Test your github actions locally

https://github.com/nektos/act

